name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: common
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          working-directory: internal/common
      - name: books
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          working-directory: internal/books